// <auto-generated />
namespace Market.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _22345 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22345));
        
        string IMigrationMetadata.Id
        {
            get { return "202110111242317_22345"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
